server:
  port: 8000  # Порт, на котором будет работать ваш API Gateway

spring:
  application:
    name: api-gateway  # Имя вашего приложения
  cloud:
    gateway:
      routes:
        - id: team_service_route
          uri: lb://team-service
          predicates:
            - Path=/team-service/**
      discovery:
        locator:
          enabled: true  # Включает автоматическое обнаружение маршрутов из Eureka
          lower-case-service-id: true  # Преобразует ID сервисов в нижний регистр
      httpclient:
        connect-timeout: 5000  # Таймаут соединения в миллисекундах (5 секунд)
        response-timeout: 3000  # Таймаут ожидания ответа (3 секунды)
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: [ "*" ]  # Разрешает доступ с любого домена
            allowCredentials: true
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - OPTIONS

eureka:
  instance:
    lease-renewal-interval-in-seconds: 10  # частота отправки heartbeats, по умолчанию 30
    lease-expiration-duration-in-seconds: 90  # время ожидания перед отключением инстанса, по умолчанию 90
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # URL вашего Eureka сервера
    fetch-registry: true  # Включает получение реестра сервисов из Eureka
    register-with-eureka: true  # Регистрирует этот сервис в Eureka

logging:
  level:
    org.springframework.cloud.gateway: DEBUG  # Устанавливает уровень логирования для шлюза
    reactor.netty.http.client: DEBUG  # Устанавливает уровень логирования для HTTP клиента Netty
